export const AESPA_NUMBER = 4;
export const AESPA_MEMBERS_LIST_FOR_FILTER = [
  `Karina`,
  `Winter`,
  `Ningning`,
  `Giselle`,
];
export const AESPA_EMOJI_LIST = [`❤`, `⭐`, `🦋`, `🌙`];

export const AESPA_TITLES_LIST = [
  `Black Mamba`,
  `Next Level`,
  `Savage`,
  `Dreams Come True`,
  `Illusion`,
  `Girls`,
  `Spicy`,
  `Drama`,
  `Supernova`,
  `Armageddon`,
  `Whiplash`,
];
export const AESPA_ALL_SONGS_LIST = [
  `MIROTIC (TVXQ!)`,
  `MIROTIC`,
  `step back`,
  `stamp on it`,
  `UP`,
  `Menagerie`,
  `Lips`,
  `Spark`,
  `Wake Up`,
  `Bored`,
  `we go`,
  `DOPAMINE`,
  `2HOT4U`,
  `Black Mamba`,
  `블랙맘바`,
  `Dreams Come True`,
  `dream come true`,
  `드림스컴트루`,
  `드림스 컴 트루`,
  `약속`,
  `Forever`,
  `Savage`,
  `세비지`,
  `Next Level`,
  `aenergy`,
  `ænergy`,
  `I’ll Make You Cry`,
  `I'll Make You Cry`,
  `YEPPI YEPPI`,
  `예삐예삐`,
  `ICONIC`,
  `Lucid Dream`,
  `자각몽`,
  `Illusion`,
  `도깨비불`,
  `Life's Too Short`,
  `Life’s Too short`,
  `life is too short`,
  `Girls`,
  `도깨비불`,
  `Illusion`,
  `lllusion`,
  `Lingo`,
  `ICU`,
  `쉬어가도 돼`,
  `Beautiful Christmas`,
  `Hold On Tight`,
  `Welcome to MY World`,
  `Spicy`,
  `Salty & Sweet`,
  `salty and sweet`,
  `Thirsty`,
  `thirtsy`,
  `I'm Unhappy`,
  `I’m Unhappy`,
  `'Till We Meet Again`,
  `Till We Meet Again`,
  `‘Till We Meet Again`,
  `Better Things`,
  `Drama`,
  `Trick Or Trick`,
  `Don't Blink`,
  `Don’t Blink`,
  `Hot Air Ballon`,
  `Hot Air Balloon`,
  `YOLO`,
  `Jingle Bell Rock`,
  `Regret of the Times`,
  `시대유감`,
  `時代遺憾`,
  `Die Trying`,
  `Supernova`,
  `Armageddon`,
  `armagendon`,
  `Set The Tone`,
  `Mine`,
  `Licorice`,
  `BAHAMA`,
  `Long Chat`,
  `Prologue`,
  `Live My Life`,
  `목소리`,
  `Melody`,
  `Hot Mess`,
  `Sun and Moon`,
  `ZOOM ZOOM`,
  `Whiplash`,
  `Kill It`,
  `Flights, Not Feelings`,
  `Pink Hoodie`,
  `Flowers`,
  `Just Another Girl`,
];
export const AESPA_MEMBERS_LIST = [
  `Karina`,
  `Yu Ji-min`,
  `Yu Jimin`,
  `Yu Ji min`,
  `YuJimin`,
  `카리나`,
  `유지민`,
  `カリナ`,
  `Winter`,
  `Kim Min-jeong`,
  `Kim Minjeong`,
  `Kim Min jeong`,
  `KimMinjeong`,
  `김민정`,
  `윈터`,
  `ウィンター`,
  `Ningning`,
  `Ning Yi Zhuo`,
  `Ning Yizhuo`,
  `NingYizhuo`,
  `宁艺卓`,
  `寧藝卓`,
  `宁 艺卓`,
  `寧 藝卓`,
  `닝닝`,
  `ニンニン`,
  `宁宁`,
  `Giselle`,
  `Uchinaga Eri`,
  `UchinagaEri`,
  `内永 枝利`,
  `内永枝利`,
  `Kim Aeri`,
  `김지젤`,
  `김애리`,
  `지젤`,
  `ジゼル`,
];

export const aespa_gradient_first = "#ffffff"; // белый
export const aespa_gradient_second = "#c98bdb"; // фиолетовый
export const aespa_gradient_trird = "#5BC2E7"; // голубой

export const aespa_gradient =
  "linear-gradient(to right bottom, #ffffff, #efebfc, #e2d6f7, #d8c0f1, #d0aae9, #c4a5eb, #b6a1ec, #a79dee, #8ca9f5, #73b3f5, #61bbf0, #5bc2e7)";
