export const BABYMONSTER_NUMBER = 7;
export const BABYMONSTER_MEMBERS_LIST_FOR_FILTER = [
  `Ruka`,
  `Pharita`,
  `Asa`,
  `Ahyeon`,
  `Rami`,
  `Rora`,
  `Chiquita`,
];
export const BABYMONSTER_EMOJI_LIST = [
  `🦥`,
  `🦌`,
  `🐰`,
  `🦋`,
  `🐬`,
  `🐼`,
  `🐈‍`,
];

export const BABYMONSTER_TITLES_LIST = [
  `BATTER UP`,
  `SHEESH`,
  `FOREVER`,
  `DRIP`,
];
export const BABYMONSTER_ALL_SONGS_LIST = [
  `DREAM`,
  `BATTER UP`,
  `Stuck In The Middle`,
  `SHEESH`,
  `LIKE THAT`,
  `FOREVER`,
  `CLICK CLAK`,
  `DRIP`,
  `Love, Maybe`,
  `Love Maybe`,
  `Really Like You`,
  `BILLIONAIRE`,
  `Love In My Heart`,
  `Woke Up In Tokyo (RUKA & ASA)`,
  `Woke Up In Tokyo`,
];
export const BABYMONSTER_MEMBERS_LIST = [
  `Ruka`,
  `Kawai Ruka`,
  `KawaiRuka`,
  `루카`,
  `河井瑠花`,
  `ルカ`,
  `Pharita`,
  `PharitaBoonpakdeethaveeyod`,
  `Boonpakdeethaveeyod`,
  `파리타`,
  `ภริตา บุญภักดีทวียศ`,
  `ภาริตา`,
  `パリタ`,
  `Asa`,
  `Enami Asa`,
  `EnamiAsa`,
  `에나미 아사`,
  `榎並杏紗`,
  `榎並 杏紗`,
  `아사`,
  `アサ`,
  `Ahyeon`,
  `郑雅贤`,
  `郑 雅贤`,
  `Zhèng Yǎxián`,
  `정아현`,
  `Jung A-hyeon`,
  `Jung Ahyeon`,
  `Jung A hyeon`,
  `JungAhyeon`,
  `아현`,
  `アヒョン`,
  `Rami`,
  `라미`,
  `Haram`,
  `하람`,
  `Shin Ha-ram`,
  `Shin Haram`,
  `Shin Ha ram`,
  `ShinHaram`,
  `신하람`,
  `ラミ`,
  `Rora`,
  `ローラ`,
  `Lǐ Chárén`,
  `李 茶仁`,
  `Lee Da-in`,
  `Lee Da in`,
  `Lee Dain`,
  `LeeDain`,
  `이다인`,
  `로라`,
  `Chiquita`,
  `치키타`,
  `チキータ`,
  `Riracha Phondechaphiphat`,
  `RirachaPhondechaphiphat`,
  `ริรชา พรเดชาพิพัฒ`,
  `ริรชาพรเดชาพิพัฒ`,
];

export const babymonster_gradient_first = "#ffe4de"; // 1
export const babymonster_gradient_second = "#da303a"; // оранжевый

export const babymonster_gradient =
  "linear-gradient(to right bottom, #ffe4de, #f3c6be, #edb8af, #e49c93, #e28e85, #df8078, #df6f68, #de5d58, #da303a)";
