export const FROMIS_9_NUMBER = 8;
export const FROMIS_9_MEMBERS_LIST_FOR_FILTER = [
  `Saerom`,
  `Hayoung`,
  `Jiwon`,
  `Jisun`,
  `Seoyeon`,
  `Chaeyoung`,
  `Nagyung`,
  `Jiheon`,
];
export const FROMIS_9_EMOJI_LIST = [
  `🦊`,
  `🍞`,
  `🐰`,
  `🐑`,
  `🐼`,
  `🐿`,
  `🐣`,
  `🍯`,
  `🐶`,
];

export const FROMIS_9_TITLES_LIST = [
  `To Heart`,
  `DKDK`,
  `Love Bomb`,
  `Fun!`,
  `Feel Good`,
  `WE GO`,
  `Talk & Talk`,
  `DM`,
  `Stay This Way`,
  `#menow`,
  `Supersonic`,
];
export const FROMIS_9_ALL_SONGS_LIST = [
  `feel my rhythm`,
  `Glass Shoes`,
  `유리구두`,
  `The Way To Me`,
  `나에게로 오는 길`,
  `To Heart`,
  `Miracle`,
  `환상속의 그대`,
  `Pinocchio`,
  `Be With You`,
  `Close To You`,
  `다가가고 싶어`,
  `Think of You`,
  `너를 따라, 너에게`,
  `DKDK`,
  `Pit-a-pat`,
  `Pitapat`,
  `두근두근`,
  `22Century Girl`,
  `22 세기 소녀`,
  `22세기 소녀`,
  `Clover`,
  `First Love`,
  `Love Bomb`,
  `Dancing Queen`,
  `Coloring`,
  `물들어`,
  `Fun!`,
  `Fun`,
  `Love Rumpumpum`,
  `Rumpumpum`,
  `Fly High`,
  `Feel Good`,
  `Secret Code`,
  `Weather`,
  `Starry Night`,
  `별의 밤`,
  `Somebody to Love`,
  `Mulgogi`,
  `물고기`,
  `Airplane Mode`,
  `WE GO`,
  `Promise`,
  `Talk & Talk`,
  `Star`,
  `별`,
  `Escape Room`,
  `DM`,
  `Love Is Around`,
  `Hush Hush`,
  `0g`,
  `Up And`,
  `Stay This Way`,
  `Blind Letter`,
  `Cheese`,
  `Rewind`,
  `Sea of Moonlight`,
  `달빛바다`,
  `Attitude`,
  `#menow`,
  `menow`,
  `Wishlist`,
  `In the Mirror`,
  `Don’t Care`,
  `Don't Care`,
  `Prom Night`,
  `Bring It On`,
  `What I Want`,
  `My Night Routine`,
  `눈맞춤`,
  `Eye Contact`,
  `Supersonic`,
  `Beat the Heat`,
  `Take A Chance`,
];
export const FROMIS_9_MEMBERS_LIST = [
  `Lee Sae Rom`,
  `Lee Sae-Rom`,
  `Lee SaeRom`,
  `LeeSaeRom`,
  `Saerom`,
  `이새롬`,
  `새롬`,
  `SONG HA YOUNG`,
  `SONG HA-YOUNG`,
  `SONG HAYOUNG`,
  `SONGHAYOUNG`,
  `Hayoung`,
  `송하영`,
  `하영`,
  `PARK JI WON`,
  `PARK JI-WON`,
  `PARK JIWON`,
  `PARKJIWON`,
  `Jiwon`,
  `박지원`,
  `지원`,
  `RHO JI SUN`,
  `RHO JI-SUN`,
  `ROH JISUN`,
  `ROHJISUN`,
  `Jisun`,
  `노지선`,
  `지선`,
  `LEE SEOYEON`,
  `LEE SEO YEON`,
  `LEE SEO-YEON`,
  `LEE SEOYEON`,
  `Seoyeon`,
  `이서연`,
  `서연`,
  `LEE CHAE YOUNG`,
  `LEE CHAE-YOUNG`,
  `LEE CHAEYOUNG`,
  `LEECHAEYOUNG`,
  `Chaeyoung`,
  `이채영`,
  `채영`,
  `LEE NA GYUNG`,
  `LEE NA-GYUNG`,
  `LEE NAGYUNG`,
  `LEENAGYUNG`,
  `Nagyung`,
  `이나경`,
  `나경`,
  `BAEK JI HEON`,
  `BAEK JI-HEON`,
  `BAEK JIHEON`,
  `BAEKJIHEON`,
  `Jiheon`,
  `백지헌`,
  `지헌`,
  `JANG GYU RI`,
  `JANG GYU-RI`,
  `JANG GYURI`,
  `JANGGYURI`,
  `Gyuri`,
  `장규리`,
  `규리`,
];

export const fromis_9_gradient_first = "#f1f3f5"; // серый
export const fromis_9_gradient_second = "#c73b32"; // красно-оранжевый

export const fromis_9_gradient = `linear-gradient(to right bottom, #f1f3f5, #e2e5f1, #ded4ea, #e1c1d9, #e6aebe, #e69fa9, #e39191, #dc8476, #d87364, #d36253, #cd4f42, #c73b32)`;
