import {
  IdolSongTagSvg,
  IdolTagSvg,
  PerfomanceTagSvg,
  SongTagSvg,
} from "../icons/SiteTags";

export const HEADER_HEIGHT = 20;
export const HEADER_COLOR = `rgba(0,0,0, 0.01)`;

// eslint-disable-next-line
export const REGEX_BOUNDARIES = `[.\\s()[\\]\\\+"“”“”（）「」［］〝〞˚°xX’‘\\/＜＞직♥【】@_《》♬&:+✧💫❤️‍🔥👀⭐⚠️❣️🎥⏯️🥰💜🤍🌸🔊💖🎼🎧✨🎵#＃♫«»‹›｜│ㅣ!－,–'-—]`;
export const KEY_FOR_FRONT = `AIzaSyDs7g9XZmyQMuDe88UGz5iWnA2GiVsqeUY`;
export const KEY_FOR_BACK = `AIzaSyC0sb9VEQIiJOhM3iJffQ-riHhZ6WaisSs`;

export const Z_INDEX_1 = 1;
export const Z_INDEX_2 = 10;
export const Z_INDEX_3 = 100;
export const Z_INDEX_4 = 1000;
export const Z_INDEX_5 = 10000;

export const MAX_PREVIEW_WIDTH = `354px`;
export const MAX_PREVIEW_HEIGHT = `199px`;

export const MIN_PREVIEW_WIDTH = `320px`;
export const MIN_PREVIEW_HEIGHT = `179px`;

export const SITE_TAGS_ARRAY_0 = [
  "mostViewedIdol",
  "mostViewedSong",
  "mostViewedIdolSong",
  "mostViewedPerfomance",
];

export const SITE_TAGS_ARRAY_FOR_NAMES_0 = [
  IdolTagSvg,
  SongTagSvg,
  IdolSongTagSvg,
  PerfomanceTagSvg,
];

export const SITE_TAGS_ARRAY_1 = [
  `official`,
  `fancam`,
  `perfomance`,
  `facecam`,
  `fullcam`,
  `visualcam`,
  `encore`,
  `choreography`,
  `stagemix`,
  `university`,
  `studiochoom`,
];

export const SITE_TAGS_ARRAY_2 = [
  `voicecam360`,
  `waterbomb`,
  `mbcgayodaejejeon`,
  `kbsgayodaechukje`,
  `sbsgayodaejeon`,
  `hanteomusicawards`,
  `thefactmusicawards`,
  `geniemusicawards`,
  `mtvvideomusicawards`,
  `billboard`,
];
export const SITE_TAGS_ARRAY_FOR_INPUTS_0 = [
  "Только самые просматриваемые у айдола",
  "Только самые просматриваемые на песню",
  "Только самые просматриваемые на песню по айдолу",
  "Только самые просматриваемые перфомансы ",
];

export const SITE_TAGS_ARRAY_FOR_INPUTS_1 = [
  `Official`,
  `Fancam`,
  `Perfomance`,
  `FaceCam`,
  `FullCam`,
  `VisualCam`,
  `Encore`,
  `Choreography`,
  `StageMix`,
  `University`,
  `Studio CHOOM`,
];

export const SITE_TAGS_ARRAY_FOR_INPUTS_2 = [
  `VoiceCam360`,
  `Waterbomb`,
  `MBC Gayo Daejejeon`,
  `KBS Gayo Daechukje`,
  `SBS Gayo Daejeon`,
  `Hanteo Music Awards`,
  `The Fact Music Awards`,
  `Genie Music Awards`,
  `MTV Music Awards`,
  `Billboard`,
];

export const FORBIDDEN_WORDS = [
  `컴백 기념`,
  `주년 메시지`,
  `축하 메시지`,
  `tutorial`,
  `I-LAND2`,
  `셀프 메이드 테스트`,
  `Videodump`,
  `자기소개 및 멘트`,
  `자기소개`,
  `멘트`,
  `뮤직뱅크 퇴근`,
  `중간대화`,
  `Photo Session`,
  `PhotoSession`,
  `댓글 모음`,
  `댓글모음`,
  `kpop fap`,
  `비릭비디오`,
  `랜덤플레이댄스FULL`,
  `brand film`,
  `concept film`,
  `thank you stage`,
  `썸썸썸`,
  `K-Fashion Pavilion`,
  `MC석 인터뷰`,
  `MC석 코너`,
  `かなるび`,
  `fanchant`,
  `live clip`,
  `SPECIAL CLIP`,
  `line distribution`,
  `lyrics`,
  `color coded`,
  `colorcoded`,
  `Invitation`,
  `인사 영상`,
  `인사영상`,
  `중간인사`,
  `멘트`,
  `ment`,
  `talking`,
  `마지막멘트`,
  `마지막 멘트`,
  `무대인사`,
  `인사`,
  `엔딩멘트`,
  `엔딩멘`,
  `소감`,
  `개인소감`,
  `마무리 토크`,
  `마무리토크`,
  `중간 멘트`,
  `중간멘트`,
  `오프닝`,
  `opening`,
  `ending`,
  `중간멘트`,
  `무대인사`,
  `엔딩무대`,
  `비하인드더쇼`,
  `비하인드`,
  `비하인드 더 쇼`,
  `아이돌.zip`,
  `Mwave shop`,
  `딘딘의 뮤직하이`,
  `반모하show`,
  `보는 라디오`,
  `수상소감`,
  `본상`,
  `k-hotties`,
  `mr removed`,
  `Mr. Removed`,
  `special video`,
  `track video`,
  `vlog`,
  `Preview`,
  `Lyric Video`,
  `응원법`,
  `reaction`,
  `track poster`,
  `Mood Sampler`,
  `original song by.`,
  `original song by`,
  `unboxing`,
  `official audio`,
  `cheering guide`,
  `highlight medley`,
  `아는 형님`,
  `인터뷰`,
  `#shorts`,
  `엔딩무대`,
  `kpopfap`,
  `tribute`,
  `Jelly Jelly`,
  `ckhero`,
  `artist message`,
  `cover`,
  `Red Carpet`,
  `이런뉴스`,
  `선공개`,
  `Mirrored`,
  `Challenge`,
  `도전하다`,
  `도전`,
  `Teaser`,
  `Behind`,
  `Interview`,
  `MV`,
  `M/V`,
  `Music Video`,
  `Phototime`,
  "Airport",
  "Departure",
  "Arrival",
  "입국",
  `GMP 입국`,
  `GMP입국`,
  `입국 GMP`,
  `입국GMP`,
  "Baseball",
  "잠실야구장",
  "김포공항",
  "김포국제공항",
  "출국",
  "Knowing bros",
  "Photo time",
  "Long walk",
  "Longwalk",
  "포토월",
  "퇴근길",
  `뮤직뱅크 퇴근`,
  "Photocall",
  "Photo call",
  `포토콜`,
  "출근길",
  `보테가베네타`,
  `보테가 베네타`,
  `퇵길아웃! : 퇴근럽웅`,
  `퇴근파서블`,
  `off air`,
  `karaoke`,
  `ending`,
  `ending part`,
  `stage talk`,
];
