export const GIDLE_NUMBER = 5;
export const GIDLE_MEMBERS_LIST_FOR_FILTER = [
  `Soyeon`,
  `Minnie`,
  `Miyeon`,
  `Yuqi`,
  `Shuhua`,
];
export const GIDLE_EMOJI_LIST = [`🦁`, `🐭`, `🐰`, `🦒`, `🐺`];

export const GIDLE_TITLES_LIST = [
  `LATATA`,
  `HANN (Alone)`,
  `Senorita`,
  `Uh-Oh`,
  `LION`,
  `Oh My God`,
  `DUMDi DUMDi`,
  `HWAA`,
  `Tomboy`,
  `Nxde`,
  `QUEENCARD`,
  `Super Lady`,
  `Fate`,
  `Klaxon`,
];
export const GIDLE_ALL_SONGS_LIST = [
  // eslint-disable-next-line
  `pop\/stars`,
  `pop/stars`,
  `pop/star`,
  // eslint-disable-next-line
  `pop\/star`,
  `POPSTARS`,
  `sanorita`,
  "마음이 닿는 법",
  "How To Love",
  `Señorita`,
  `Sky Walking`,
  `DAHLIA`,
  `달리아`,
  `Change`,
  `Like A Dream`,
  `꿈결같아서`,
  `Is This Bad Bitch Number`,
  `Is This Bad B Number`,
  `Is This Bad B`,
  `Radio`,
  `Jelly`,
  `Beam Beam (삠삠)`,
  `Beam Beam`,
  `삠삠`,
  `Weather`,
  `Quit`,
  `Psycho`,
  `Rose`,
  `Drive`,
  `Softly`,
  `TE AMO`,
  `Charging`,
  `소나기 (Rain)`,
  `소나기`,
  `Rain`,
  `Giant`,
  `Bonnie & Clyde`,
  `Freak`,
  `My Way`,
  `Drink It Up`,
  `Red Rover`,
  `On Clap`,
  `Everytime`,
  `Could It Be`,
  `Expectations`,
  `Boys`,
  `LATATA`,
  `𝗟𝗔𝗧𝗔𝗧𝗔`,
  `달라`,
  `DOLLAR`,
  `Maze`,
  `Don’t Text Me`,
  `What’s In Your House`,
  `알고 싶어`,
  `Hear Me`,
  `들어줘요`,
  `Alone`,
  `Senorita`,
  `What’s Your Name`,
  `Put It Straight`,
  `싫다고 말해`,
  `Give Me Your`,
  `주세요`,
  `Blow Your Mind`,
  `Uh-Oh`,
  `Uh Oh`,
  `UhOh`,
  `Light My Fire`,
  `For You`,
  `LION`,
  `Oh My God`,
  `Luv U`,
  `사랑해`,
  `Maybe`,
  `i’M THE TREND`,
  `DUMDi DUMDi`,
  `덤디덤디`,
  `Tung-Tung (Empty)`,
  `Empty`,
  `Tung-Tung`,
  `한(一)`,
  `HANN (Alone)`,
  `一`,
  `Hann (Alone in winter)`,
  `Alone in winter`,
  `한(寒)`,
  `寒`,
  `HWAA`,
  `화`,
  `火花`,
  `Moon`,
  `Where is love`,
  `Lost`,
  `Dahlia`,
  `Last Dance`,
  `Tomboy`,
  `Never Stop Me`,
  `말리지 마`,
  `Villain Dies`,
  `Already`,
  `Polaroid`,
  `Escape`,
  `Liar`,
  `My Bag`,
  `Nxde`,
  `Change`,
  `Reset” – 3:0`,
  `Reset`,
  `조각품`,
  `Sculpture`,
  `Dark (X-file)`,
  `Dark`,
  `X-file`,
  `Reset`,
  `퀸카 (QUEENCARD)`,
  `퀸카`,
  `QUEENCARD`,
  `ALLERGY`,
  `LUCID`,
  `ALL NIGHT`,
  `PARADISE`,
  `PETER PAN`,
  `어린 어른`,
  `I Want That`,
  `Eyes Roll`,
  `Flip It`,
  `Tall Trees`,
  `Super Lady`,
  `Revenge`,
  `Doll`,
  `Vision`,
  `7 Days`,
  `나는 아픈 건 딱 질색이니까 (Fate)`,
  `나는 아픈 건 딱 질색이니까`,
  `Fate`,
  `Rollie`,
  `Wife`,
  `Abracadabra`,
  `클락션 (Klaxon)`,
  `클락션`,
  `Klaxon`,
  `Last Forever`,
  `Bloom`,
  `Neverland`,
];
export const GIDLE_MEMBERS_LIST = [
  `Soyeon`,
  `소연`,
  `Jeon So-yeon`,
  `Jeon Soyeon`,
  `Jeon So yeon`,
  `JeonSoyeon`,
  `전소연`,
  `ソヨン`,
  `Minnie`,
  `민니`,
  `Kim Min-hee`,
  `Kim Minhee`,
  `김민희`,
  `Nicha Yontararak`,
  `NichaYontararak`,
  `มินนี่ ณิชา ยนตรรักษ์`,
  `มินนี่ณิชายนตรรักษ์`,
  `ミンニ`,
  `มินนี่`,
  `Miyeon`,
  `미연`,
  `Cho Mi-yeon`,
  `Cho Mi Yeon`,
  `Cho Miyeon`,
  `ChoMiyeon`,
  `조미연`,
  `ミヨン`,
  `Yuqi`,
  `우기`,
  `ウギ`,
  `雨琦`,
  `Sòng Yǔ Qí`,
  `Sòng YǔQí`,
  `Song YuQi`,
  `SongYuQi`,
  `宋雨琦`,
  `宋 雨琦`,
  `Song Woo-gi`,
  `Song Woogi`,
  `송우기`,
  `Shuhua`,
  `슈화`,
  `シュファ`,
  `Yoo Su-hwa`,
  `Yoo Suhwa`,
  `유수화`,
  `Yè Shūhuá`,
  `YèShūhuá`,
  `YeShuhua`,
  `Ye Shuhua`,
  `Ye Shu Hua`,
  `Yeh Shu Hua`,
  `YehShuHua`,
  `Yeh ShuHua`,
  `叶舒华`,
  `叶 舒华`,
  `Soojin`,
  `수진`,
  `スジン`,
  `Seo Soo-Jin`,
  `Seo SooJin`,
  `SeoSooJin`,
  `Seo Soo Jin`,
  `서수진`,
];

export const gidle_gradient_first = "#ffffff"; // белый
export const gidle_gradient_second = "#e4002b"; // Neon Red
export const gidle_gradient_trird = "#5c068c"; // Chic Violet

export const gidle_gradient =
  "linear-gradient(to right bottom, #ffffff, #efddf9, #f0b5e4, #f78abe, #f95987, #ee4473, #e22c5f, #d6004b, #c5005e, #ac0070, #8a0080, #5c068c)";
