export const ITZY_NUMBER = 5;
export const ITZY_MEMBERS_LIST_FOR_FILTER = [
  `Yeji`,
  `Ryujin`,
  `Chaeryeong`,
  `Yuna`,
  `Lia`,
];
export const ITZY_EMOJI_LIST = [`🐈`, `🐵`, `🦊`, `🐰`, `🦥`];

export const ITZY_TITLES_LIST = [
  `Dalla Dalla`,
  `Icy`,
  `Wannabe`,
  `Not Shy`,
  `In the morning`,
  `Loco`,
  `Sneakers`,
  `Cheshire`,
  `CAKE`,
  `UNTOUCHABLE`,
  `GOLD`,
  `Imaginary Friend`,
];
export const ITZY_ALL_SONGS_LIST = [
  `hotter than hell`,
  `maniac`,
  `boss bitch`,
  `bloodline`,
  `blood line`,
  `red`,
  `You & Me`,
  `U-Go-Girl`,
  `Cry for Me`,
  `Break My Heart Myself`,
  `River`,
  `therefore i am`,
  `Dalla Dalla`,
  `달라달라`,
  `Want It?`,
  `Icy`,
  `Cherry`,
  `IT’z Summer`,
  `Wannabe`,
  `Ting Ting Ting`,
  `That’s a No No`,
  `Nobody Like You`,
  `You Make Me`,
  `I Don’t Wanna Dance`,
  `24Hrs`,
  `Not Shy`,
  `Don’t Give A What`,
  `Louder`,
  `iD`,
  `SURF`,
  `Be In Love`,
  `Trust Me`,
  `마.피.아. In the morning`,
  `In the Morning`,
  `마.피.아.`,
  `Sorry Not Sorry`,
  `Kidding Me`,
  `Wild Wild West`,
  `Shoot!`,
  `Tennis (0:0)`,
  `Break Ice`,
  `Joyful MomenT`,
  `Loco`,
  `Swipe`,
  `Sooo Lucky`,
  `#Twenty`,
  `Twenty`,
  `B [00] M-Boxx`,
  `B[OO]M-BOXX`,
  `Gas Me Up`,
  `Love Is`,
  `Chillin’ Chillin`,
  `Mirror`,
  `Voltage`,
  `Spice`,
  `Sneakers`,
  `Racer`,
  `What I Want`,
  `Free Fall`,
  `365`,
  `Domino`,
  `Blah Blah Blah`,
  `Can’t Tie Me Down`,
  `Cheshire`,
  `Snowy`,
  `Freaky`,
  `Boys Like You`,
  `BET ON ME`,
  `CAKE`,
  `None of My Business`,
  `Bratty (나쁜 애)`,
  `Bratty`,
  `나쁜 애`,
  `Psychic Lover`,
  `Kill Shot`,
  `Ringo`,
  `Sugar-holic`,
  `Playlist`,
  `Style`,
  `BORN TO BE`,
  `UNTOUCHABLE`,
  `Mr. Vampire`,
  `Dynamite`,
  `Crown On My Head (YEJI)`,
  `Crown On My Head`,
  `Blossom (LIA)`,
  `Blossom`,
  `Run Away (RYUJIN)`,
  `Run Away`,
  `Mine (CHAERYEONG)`,
  `Mine`,
  `Yet, but (YUNA)`,
  `Yet, but`,
  `Escalator`,
  `Algorhythm`,
  `No Biggie`,
  `GOLD`,
  `Imaginary Friend`,
  `Bad Girls R Us`,
  `Bad Girls are Us`,
  `Supernatural`,
  `FIVE`,
  `VAY`,
];
export const ITZY_MEMBERS_LIST = [
  `Yeji`,
  `예지`,
  `イェジ`,
  `黃禮志`,
  `黃 禮志`,
  `HwangYeji`,
  `Hwang Yeji`,
  `Hwang Ye-ji`,
  `Hwang Ye ji`,
  `황예지`,
  `Ryujin`,
  `류진`,
  `リュジン`,
  `申 留眞`,
  `申留眞`,
  `Shin Ryu-jin`,
  `Shin Ryu jin`,
  `Shin Ryujin`,
  `ShinRyujin`,
  `신류진`,
  `Chaeryeong`,
  `채령`,
  `チェリョン`,
  `李彩領`,
  `李 彩領`,
  `Lee Chae-ryeong`,
  `Lee Chae ryeong`,
  `LeeChaeryeong`,
  `Lee Chaeryeong`,
  `이채령`,
  `Yuna`,
  `유나`,
  `ユナ`,
  `申有娜`,
  `申 有娜`,
  `Shin Yuna`,
  `ShinYuna`,
  `Shin Yu-na`,
  `Shin Yu na`,
  `신유나`,
  `Lia`,
  `리아`,
  `リア`,
  `崔智壽`,
  `崔 智壽`,
  `최지수`,
  `Choi Jisu`,
  `Choi Ji-su`,
  `Choi Ji su`,
  `ChoiJisu`,
];

export const itzy_gradient_first = "#ffffff"; // белый
export const itzy_gradient_second = "#FF00FF"; // Magenta

export const itzy_gradient =
  "linear-gradient(to right, #ffffff, #eddaff, #e8b0ff, #f07bff, #ff00ff)";
