export const IVE_NUMBER = 6;
export const IVE_MEMBERS_LIST_FOR_FILTER = [
  `Wonyoung`,
  `An Yujin`,
  `Gaeul`,
  `Rei`,
  `Liz`,
  `Leeseo`,
];
export const IVE_EMOJI_LIST = [`🐰`, `🐶`, `🐿`, `🐥`, `🐈‍`, `🐯`];

export const IVE_TITLES_LIST = [
  `ELEVEN`,
  `LOVE DIVE`,
  `After LIKE`,
  `I AM`,
  `KITSCH`,
  `Baddie`,
  `HEYA`,
  `Accendio`,
  `Rebel heart`,
  `Attitude`,
];
export const IVE_ALL_SONGS_LIST = [
  `flashlight`,
  `When Will My Life Begin`,
  `Gravity`,
  `Kill this Love`,
  `That's My Girl`,
  `Supernova Love`,
  `Reality`,
  `7 rings`,
  `Wannabe`,
  `Lion Heart`,
  `Woman Like Me`,
  `Every summertime`,
  `ELEVEN`,
  `Take It`,
  `LOVE DIVE`,
  `ROYAL`,
  `After LIKE`,
  `My Satisfaction`,
  `Queen of Hearts`,
  `Blue Blood`,
  `I AM`,
  `KITSCH`,
  `Lips`,
  `Heroine`,
  `Mine`,
  `섬찟 (Hypnosis)`,
  `Hypnosis`,
  `NOT YOUR GIRL`,
  `궁금해 (Next Page)`,
  `궁금해`,
  `Next Page`,
  `Cherish`,
  `Shine With Me`,
  `WAVE`,
  `Classic`,
  `I WANT`,
  `Off the Record`,
  `Baddie`,
  `Either Way`,
  `Holy Moly`,
  `OTT`,
  `Payback`,
  `All Night`,
  `해야 (HEYA)`,
  `해야`,
  `HEYA`,
  `Accendio`,
  `Blue Heart`,
  `Ice Queen`,
  `WOW`,
  `RESET`,
  `CRUSH`,
  `Will`,
  `Rebel Heart`,
  "Flu",
  "You Wanna Cry",
  "Thank U",
  "Attitude",
  "TKO",
];
export const IVE_MEMBERS_LIST = [
  `JANG WON-YOUNG`,
  `JANG WON YOUNG`,
  `JANG WONYOUNG`,
  `JANGWONYOUNG`,
  `Wonyoung`,
  `장원영`,
  `원영`,
  `ウォニョン`,
  `張員瑛`,
  `チャン・ウォニョン`,
  `张员瑛`,
  `Zhāng Yuányīng`,
  `An Yu-jin`,
  `An Yu jin`,
  `AN YUJIN`,
  `ANYUJIN`,
  `Yujin`,
  `안유진`,
  `유진`,
  `ユジン`,
  `安兪眞`,
  `安 兪眞`,
  `アン・ユジン`,
  `Gaeul`,
  `가을`,
  `ガウル`,
  `김가을`,
  `金가을`,
  `KimGaeul`,
  `Kim Gaeul`,
  `Kim Ga-eul`,
  `Kim Ga eul`,
  `Rei`,
  `레이`,
  `レイ`,
  `Kim Rei`,
  `김레이`,
  `Naoi Rei`,
  `直井 怜`,
  `나오이 레이`,
  `나오이레이`,
  `Liz`,
  `리즈`,
  `KimJiwon`,
  `Kim Ji-won`,
  `Kim Jiwon`,
  `Kim Ji won`,
  `김지원`,
  `金志垣`,
  `Leeseo`,
  `이서`,
  `イソ`,
  `李賢瑞`,
  `Lee Hyunseo`,
  `LeeHyunseo`,
  `Lee Hyun-seo`,
  `Lee Hyun seo`,
  `이현서`,
];

export const ive_gradient_first = "#ffffff"; // белый
export const ive_gradient_second = "#01b2eb"; // голубой
export const ive_gradient_third = "#c09add"; // светло-фиолетовый

export const ive_gradient =
  "linear-gradient(to right bottom, #ffffff, #d1dcfb, #afcef9, #75baf4, #79a9f1, #94a4ed, #ac9fe6, #c09add)";
