export const KEPLER_NUMBER = 9;
export const KEPLER_MEMBERS_LIST_FOR_FILTER = [
  `Yujin`,
  `Xiaoting`,
  `Chaehyun`,
  `Dayeon`,
  `Hikaru`,
  `Bahiyyih`,
  `Youngeun`,
  `Mashiro`,
  `Yeseo`,
];
export const KEPLER_EMOJI_LIST = [
  `🐰`,
  `🦌`,
  `🐯`,
  `🐿`,
  `🐶`,
  `🦁`,
  `🦊`,
  `🦝`,
  `🐰`,
];

export const KEPLER_TITLES_LIST = [
  `WA DA DA`,
  `Up!`,
  `We Fresh`,
  `I Do! Do You?`,
  `Giddy`,
  `Galileo`,
  `Shooting Star`,
];
export const KEPLER_ALL_SONGS_LIST = [
  `뱀`,
  `Snake`,
  `See the light`,
  `WA DA DA`,
  `MVSK`,
  `Shine`,
  `Another dream`,
  `O.O.O`,
  `Over&Over&Over`,
  `Up!`,
  `LE VOYA9E`,
  `Attention`,
  `Good Night`,
  `Rewind`,
  `Wing Wing`,
  `Daisy`,
  `Sugar Rush`,
  `We Fresh`,
  `Lion Tamer`,
  `Downtown`,
  `Dreams`,
  `THE GIRLS`,
  `I Do! Do You?`,
  `​tOgether fOrever`,
  `Giddy`,
  `LVLY`,
  `Back to the City`,
  `Why`,
  `Happy Ending`,
  `Galileo`,
  `The Door`,
  `Love on Lock`,
  `Tropical Light`,
  `TAPE`,
  `Grand Prix`,
  `Sugar`,
  `Straight Line`,
  `Grand Prix`,
  `Celebrate`,
  `Highlight`,
  `Cruise`,
  `Don’t Lose Your Smile`,
  `Last Carnival`,
  `Shooting Star`,
  `Curious`,
  `Flowers, Flutter, Your Heart`,
  `Double Up!`,
  `PUSH BUTTON`,
  `PROBLEM`,
  `Dear Diary`,
  "Sync-Love",
  "Sync Love",
  "Tipi-Tap",
  "Tipi Tap",
  "Drip",
  "Bitter Taste",
  "Heart Surf",
];
export const KEPLER_MEMBERS_LIST = [
  `CHOIYUJIN`,
  `CHOI YUJIN`,
  `Yujin`,
  `최유진`,
  `유진`,
  `ユジン`,
  `SHEN XIAOTING`,
  `SHEN XIAO TING`,
  `SHENXIAOTING`,
  `Xiaoting`,
  `샤오팅`,
  `沈小婷`,
  `シャオティン`,
  `KIM CHAEHYUN`,
  `KIMCHAEHYUN`,
  `KIM CHAE HYUN`,
  `Chaehyun`,
  `김채현`,
  `채현`,
  `チェヒョン`,
  `KIM DAYEON`,
  `KIMDAYEON`,
  `KIM DA YEON`,
  `Dayeon`,
  `김다연`,
  `다연`,
  `ダヨン`,
  `Hikaru`,
  `히카루`,
  `ひかる`,
  `Huening Bahiyyih`,
  `Bahiyyih`,
  `휴닝바히에`,
  `바히에`,
  `ヒュニンバヒエ`,
  `バヒエ`,
  `SEO YOUNGEUN`,
  `SEO YOUNG EUN`,
  `SEOYOUNGEUN`,
  `Youngeun`,
  `서영은`,
  `영은`,
  `ヨンウン`,
  `Mashiro`,
  `마시로`,
  `舞白`,
  `KANG YESEO`,
  `KANG YE SEO`,
  `KANGYESEO`,
  `Yeseo`,
  `강예서`,
  `예서`,
  `イェソ`,
];

export const kepler_gradient_first = "#ffffff"; // белый
export const kepler_gradient_second = "#f1e6b2"; // Yellow
export const kepler_gradient_third = "#c1a7e2"; // Lavender

export const kepler_gradient =
  "linear-gradient(to right bottom, #ffffff, #fff7fd, #ffeef3, #ffe7e0, #ffe4cb, #ffddbf, #ffd5b4, #ffcea9, #ffbdb0, #fdb0c0, #e7a8d3, #c1a7e2)";
