export const KISS_OF_LIFE_NUMBER = 4;
export const KISS_OF_LIFE_MEMBERS_LIST_FOR_FILTER = [
  `Julie`,
  `Natty`,
  `Belle`,
  `Haneul`,
];
export const KISS_OF_LIFE_EMOJI_LIST = [`🐱`, `🖤`, `🧚🏼`, `🦋`];

export const KISS_OF_LIFE_TITLES_LIST = [
  `Shhh`,
  `Bad News`,
  `Nobody Knows`,
  `Midas Touch`,
  `Sticky`,
  `Get Loud`,
  `Igloo`,
];
export const KISS_OF_LIFE_ALL_SONGS_LIST = [
  `taxi blurr`,
  `쉿 (Shhh)`,
  `쉿`,
  `Shhh`,
  `안녕,네버랜드 (Bye My Neverland)`,
  `안녕,네버랜드`,
  `안녕, 네버랜드`,
  `Bye My Neverland`,
  `Sugarcoat (NATTY Solo)`,
  `Sugarcoat`,
  `Countdown (BELLE Solo)`,
  `Countdown`,
  `Kitty Cat (JULIE Solo)`,
  `Kitty Cat`,
  `Play Love Games (HANEUL Solo)`,
  `Play Love Games`,
  `Bad News`,
  `Nobody Knows`,
  `My 808`,
  `TTG`,
  `Gentleman`,
  `Says It`,
  `Midas Touch`,
  `Nothing`,
  `Sixth Sense`,
  `Sticky`,
  `Te Quiero`,
  `SUPERPOWER`,
  `Maestro of My Heart`,
  `Get Loud`,
  `R.E.M`,
  `Chemistry`,
  `Igloo`,
  `lgloo`,
  `Too Many Alex`,
  `Back to Me`,
  `No One But Us`,
];
export const KISS_OF_LIFE_MEMBERS_LIST = [
  `Julie`,
  `쥴리`,
  `Julie Han`,
  `Han Julie`,
  `쥴리한`,
  `한줄리`,
  `韓줄리`,
  `Natty`,
  `나띠`,
  `นัตตี้`,
  `낫띠`,
  `อาณัชญา สุพุทธิพงศ์`,
  `อาณัชญาสุพุทธิพงศ์`,
  `아낫차야 수푸티`,
  `아낫차야수푸티`,
  `Ahnatchaya Suputhipong`,
  `AhnatchayaSuputhipong`,
  `Belle`,
  `벨`,
  `ShimHyewon`,
  `Shim Hyewon`,
  `Shim Hye won`,
  `Shim Hye-won`,
  `심혜원`,
  `Annabelle Shim`,
  `애나벨 혜원 심`,
  `沈寭園`,
  `Haneul`,
  `하늘`,
  `WonHaneul`,
  `Won Haneul`,
  `Won Ha-neul`,
  `Won Ha neul`,
  `원하늘`,
  `元하늘`,
];

export const kissoflife_gradient_first = "#f7cfd5"; // 1
export const kissoflife_gradient_second = "#d92942"; // красный

export const kissoflife_gradient =
  "linear-gradient(to right, #f7cfd5, #eaa4a9, #e58d93, #e17f77, #e06b64, #dd5551, #da3b3f, #d92942)";
