export const LE_SSERAFIM_NUMBER = 5;
export const LE_SSERAFIM_MEMBERS_LIST_FOR_FILTER = [
  `Chaewon`,
  `Sakura`,
  `Yunjin`,
  `Kazuha`,
  `Eunchae`,
];
export const LE_SSERAFIM_EMOJI_LIST = [`🐯`, `🐱`, `🐍`, `🦢`, `🐈`];

export const LE_SSERAFIM_TITLES_LIST = [
  `FEARLESS`,
  `ANTIFRAGILE`,
  `Impurities`,
  `UNFORGIVEN`,
  `Eve, Psyche & The Bluebeard’s Wife`,
  `No-Return`,
  `Perfect Night`,
  `EASY`,
  `Smart`,
  `Swan Song`,
  `CRAZY`,
  `HOT`,
  `Come Over`,
];
export const LE_SSERAFIM_ALL_SONGS_LIST = [
  `I AM SPECIAL`,
  `MAGO`,
  `I ≠ DOLL`,
  `love you twice`,
  `Raise y_our glass`,
  `raise your glass`,
  `good girl bad girl`,
  `Blessing in Disguise`,
  `The World Is My Oyster`,
  `FEARLESS`,
  `Blue Flame`,
  `The Great Mermaid`,
  `Sour Grapes`,
  `The Hydra`,
  `ANTIFRAGILE`,
  `Impurities`,
  `No Celestial`,
  `Good Parts (when the quality is bad but I am)`,
  `Good Parts`,
  `Choices`,
  `Burn the Bridge`,
  `UNFORGIVEN`,
  `No Return (Into the unknown)`,
  `No Return`,
  `no-return`,
  `no-return (into the unknown)`,
  `Eve, Psyche & The Bluebeard’s wife`,
  `Eve, Psyche`,
  `eptbw`,
  `이브, 프시케 그리고 푸른 수염의 아내`,
  `이브, 프시케 그리고 푸른수염의 아내`,
  `이브 프시케 그리고 푸른수염의 아내`,
  `이브, 프시케, 그리고 푸른 수염의 아내`,
  `FEARNOT`,
  `FEARNOT (Between you, me and the lamppost)`,
  `Between you, me and the lamppost`,
  `피어나`,
  `Flash Forward`,
  `Fire in the belly`,
  `Guardian`,
  `ジュエリー`,
  `Jewelry`,
  `Perfect Night`,
  `ドレスコード`,
  `Dresscode`,
  `Good Bones`,
  `EASY`,
  `Swan Song`,
  `Smart`,
  `We got so much`,
  `Chasing Lightning`,
  `CRAZY`,
  `Pierrot`,
  `1-800-hot-n-fun`,
  `1-800-hot n fun`,
  `1-800-hot & fun`,
  `hot n fun`,
  `미치지 못하는 이유 (Why I Can’t Go Crazy)`,
  `미치지 못하는 이유`,
  `Why I Can’t Go Crazy`,
  `Star Signs`,
  `Born Fire`,
  `HOT`,
  `Come Over`,
  `Ash`,
  `So Cynical`,
  `So Cynical (Badum)`,
  `Badum`,
];

export const LE_SSERAFIM_MEMBERS_LIST = [
  `Huh Yunjin`,
  `HuhYunjin`,
  `Yunjin`,
  `허윤진`,
  `ホ・ユンジン`,
  `ユンジン`,
  `Jennifer Huh`,
  `JenniferHuh`,
  `Huh Yun-jin`,
  `Huh Yun jin`,
  `許允眞`,
  `제니퍼 윤진 허`,
  `Hong Eunchae`,
  `HongEunchae`,
  `Eunchae`,
  `홍은채`,
  `ホン・ウンチェ`,
  `ウンチェ`,
  `Hong Eun-chae`,
  `Hong Eun chae`,
  `洪恩採`,
  `Kim Chaewon`,
  `KimChaewon`,
  `Chaewon`,
  `김채원`,
  `キム・チェウォン`,
  `チェウォン`,
  `Kim Chae-won`,
  `Kim Chae won`,
  `金采源`,
  `Nakamura Kazuha`,
  `NakamuraKazuha`,
  `Kazuha`,
  `카즈하`,
  `一葉/カズハ`,
  `カズハ`,
  `Kang Ju-ha`,
  `Kang Juha`,
  `강주하`,
  `中村一葉`,
  `나카무라 카즈하`,
  `Miyawaki Sakura`,
  `MiyawakiSakura`,
  `Sakura`,
  `사쿠라`,
  `咲良/サクラ`,
  `미야와키사쿠라`,
  `미야와키 사쿠라`,
  `宮脇咲良`,
  `宮脇 咲良`,
  `サクラ`,
];

export const le_sserafim_gradient_first = "#ffffff"; //белый
export const le_sserafim_gradient_second = "#81A5F9"; // синий
export const le_sserafim_gradient_third = "#212529"; // серый

export const le_sserafim_gradient =
  "linear-gradient(to right bottom, #ffffff, #dadafc, #c4c9fb, #92a7e7, #7895d4, #5e84c1, #395370, #2d3c4b, #212529)";
