export const NEWJEANS_NUMBER = 5;
export const NEWJEANS_MEMBERS_LIST_FOR_FILTER = [
  `Minji`,
  `Hanni`,
  `Danielle`,
  `Haerin`,
  `Hyein`,
];
export const NEWJEANS_EMOJI_LIST = [`🐻`, `🐰`, `🐶`, `🐱`, `🐣`];

export const NEWJEANS_TITLES_LIST = [
  `Attention`,
  `Hype Boy`,
  `Cookie`,
  `Ditto`,
  `OMG`,
  `Super Shy`,
  `ETA`,
  `How Sweet`,
  `Bubble Gum`,
  `Supernatural`,
  `Right Now`,
];
export const NEWJEANS_ALL_SONGS_LIST = [
  `'青い珊瑚礁`,
  `푸른 산호초`,
  `푸른산호초`,
  `青い珊瑚礁`,
  `Butterflies`,
  `With U`,
  `Odoriko`,
  `踊り子`,
  `Hold It Down`,
  `Plastic Love`,
  `Butterfly`,
  `Attention`,
  `Hype Boy`,
  `Cookie`,
  `Hurt`,
  `OMG`,
  `Ditto`,
  `Tell Me`,
  `Zero`,
  `Super Shy`,
  `ETA`,
  `Cool With You`,
  `Get Up`,
  `ASAP`,
  `Gods`,
  `How Sweet`,
  `Bubble Gum`,
  `Supernatural`,
  `super natural`,
  `Right Now`,
];
export const NEWJEANS_MEMBERS_LIST = [
  `Minji`,
  `민지`,
  `김민지`,
  `Kim Min-ji`,
  `Kim Minji`,
  `Kim Min ji`,
  `KimMinji`,
  `金玟池`,
  `Hanni`,
  `하니`,
  `Hanni Pham`,
  `하니 팜`,
  `하니팜`,
  `Phạm Ngọc Hân`,
  `范玉欣`,
  `Danielle`,
  `다니엘`,
  `Danielle June Marsh`,
  `다니엘 준 마시`,
  `牟智慧`,
  `모지혜`,
  `Mo Jihye`,
  `MoJihye`,
  `Mo Ji-hye`,
  `Mo Ji hye`,
  `Haerin`,
  `해린`,
  `KangHaerin`,
  `Kang Haerin`,
  `Kang Hae-rin`,
  `Kang Hae rin`,
  `강해린`,
  `姜諧潾`,
  `Hyein`,
  `혜인`,
  `LeeHyein`,
  `Lee Hyein`,
  `Lee Hye-in`,
  `Lee Hye in`,
  `이혜인`,
  `李惠仁`,
  `Li Huiren`,
];

export const newjeans_gradient_first = "#f1f3f5"; // серый
export const newjeans_gradient_second = "#7a88b8"; // тёмно-синий

export const newjeans_gradient =
  "linear-gradient(to right bottom, #f1f3f5, #d3d7e7, #b5bdd8, #97a3c8, #7a88b8)";
