export const NMIXX_NUMBER = 6;
export const NMIXX_MEMBERS_LIST_FOR_FILTER = [
  `Haewon`,
  `Jiwoo`,
  `Sullyoon`,
  `Bae`,
  `Lily`,
  `Kyujin`,
];
export const NMIXX_EMOJI_LIST = [`🐻`, `🐶`, `🐰`, `🐥`, `🐨`, `🐱`];

export const NMIXX_TITLES_LIST = [
  `O.O`,
  `Tank`,
  `DICE`,
  `Young, Dumb, Stupid`,
  `Love Me Like This`,
  `Roller Coaster`,
  `Party O’Clock`,
  `DASH`,
  `Soñar (Breaker)`,
  `See that? (별별별)`,
  `KNOW ABOUT ME`,
];
export const NMIXX_ALL_SONGS_LIST = [
  `빨간 맛`,
  `Hey Mama`,
  `You In My Blurred Memories`,
  `Tank`,
  `占`,
  `O.O`,
  `Hey Gabby!`,
  `안녕 개비!`,
  `Sprinkle Party`,
  `스프링클 파티`,
  `Kiss`,
  `DICE`,
  `COOL (your rainbow)`,
  `COOL`,
  `Funky Glitter Christmas`,
  `Young, Dumb, Stupid`,
  `Young Dumb Stupid`,
  `Love Me Like This`,
  `PAXXWORD`,
  `Just Did It`,
  `My Gosh`,
  `HOME`,
  `Roller Coaster`,
  `Party O’Clock`,
  `party o'clock`,
  `DASH`,
  `Soñar (Breaker)`,
  `Soñar`,
  `Breaker`,
  `Sonar`,
  `Run For Roses`,
  `BOOM`,
  `Passionfruit`,
  `XOXO`,
  `Break The Wall`,
  `Like Magic`,
  `FEIFEI`,
  `蜚蜚`,
  "See That? (별별별)",
  `See That?`,
  `별별별`,
  "Sickuhh",
  "Red Light Sign, But We Go",
  "Beat Beat",
  "Moving On",
  "Love is Lonely",
  `hot`,
  `Kick It`,
  `High Horse`,
  `KNOW ABOUT ME`,
  `Slingshot`,
  `Golden Recipe`,
  `Papilon`,
  `Ocean`,
];
export const NMIXX_MEMBERS_LIST = [
  `Lily`,
  `릴리`,
  `Lily Morrow`,
  `릴리 머로우`,
  `LilyMorrow`,
  `릴리머로우`,
  `パク・ジン`,
  `朴珍`,
  `Lily Jin Park Morrow`,
  `릴리 진 박 머로우`,
  `박진`,
  `朴珍`,
  `Haewon`,
  `해원`,
  `OhHaewon`,
  `Oh Haewon`,
  `Oh Hae-won`,
  `Oh Hae won`,
  `오해원`,
  `オ・ヘウォン`,
  `吳海嫄`,
  `Sullyoon`,
  `설윤`,
  `SeolYoona`,
  `Seol Yoona`,
  `Seol Yoon-a`,
  `Seol Yoon a`,
  `설윤아`,
  `ソル・ユナ`,
  `薛侖娥`,
  `Bae`,
  `배이`,
  `배진솔`,
  `裵眞率`,
  `BaeJinSol`,
  `Bae JinSol`,
  `Bae Jin-Sol`,
  `Bae Jin Sol`,
  `ペ・ジンソル`,
  `Jiwoo`,
  `지우`,
  `김지우`,
  `KimJiWoo`,
  `Kim JiWoo`,
  `Kim Ji-Woo`,
  `Kim Ji Woo`,
  `キム・ジウ`,
  `金智友`,
  `Kyujin`,
  `규진`,
  `JangKyujin`,
  `Jang Kyujin`,
  `Jang Kyu-jin`,
  `Jang Kyu jin`,
  `장규진`,
  `チャン・ギュジン`,
  `張圭珍`,
  `Jinni`,
  `Jini`,
  `지니`,
  `ChoiYunjin`,
  `Choi Yunjin`,
  `Choi Yun-jin`,
  `Choi Yun jin`,
  `최윤진`,
  `チェ・ユンジン`,
  `崔允珍`,
];

export const nmixx_gradient_first = "#e4ecfe"; // Light Periwinkle
export const nmixx_gradient_second = "#35d1e1"; // голубой

export const nmixx_gradient =
  "linear-gradient(to right, #e4ecfe, #e4ecfe, #e4ecfe, #b8ddfc, #b8ddfc, #7bd1f2, #35d1e1)";
