export const STAYC_NUMBER = 6;
export const STAYC_MEMBERS_LIST_FOR_FILTER = [
  `Sumin`,
  `Sieun`,
  `Isa`,
  `Seeun`,
  `Yoon`,
  `J`,
];
export const STAYC_EMOJI_LIST = [`🐰`, `🐩`, `🐱`, `🦊`, `🐯`, `🐶`];

export const STAYC_TITLES_LIST = [
  `So Bad`,
  `ASAP`,
  `STEREOTYPE`,
  `RUN2U`,
  `BEAUTIFUL MONSTER`,
  `POPPY`,
  `Teddy Bear`,
  `Bubble`,
  `Cheeky Icy Thang`,
  `GPT`,
  `BEBE`,
];
export const STAYC_ALL_SONGS_LIST = [
  `my dream patissiere`,
  `So Bad`,
  `Like This`,
  `ASAP`,
  `So What`,
  `Love Fool`,
  `사랑은 원래 이렇게 아픈 건가요`,
  `색안경`,
  `STEREOTYPE`,
  `I’LL BE THERE`,
  `SLOW DOWN`,
  `COMPLEX`,
  `RUN2U`,
  `SAME SAME`,
  `247`,
  `YOUNG LUV`,
  `BUTTERFLY`,
  `I WANT U BABY`,
  `BEAUTIFUL MONSTER`,
  `I LIKE IT`,
  `POPPY`,
  `Teddy Bear`,
  `Bubble`,
  `Not Like You`,
  `I Wanna Do`,
  `Be Mine`,
  `LIT`,
  `Twenty`,
  `Cheeky Icy Thang`,
  `1 Thing`,
  `Give It 2 Me`,
  `Find (SIEUN, SEEUN, & J)`,
  `Find`,
  `Let Me Know`,
  `Nada`,
  `Fakin’ (SUMIN & YOON)`,
  `Fakin’`,
  `Roses (ISA)`,
  `Roses`,
  `Beauty Bomb`,
  `Gummy Bear`,
  `Stay WITH me`,
  `Flexing On My Ex`,
  `Trouble Maker`,
  `Meow`,
  `GPT`,
  `Tell Me Now`,
  `BEBE`,
  `DIAMOND`,
  `PIPE DOWN`,
];
export const STAYC_MEMBERS_LIST = [
  `Sumin`,
  `수민`,
  `BaeSumin`,
  `Bae Sumin`,
  `Bae Su-min`,
  `Bae Su min`,
  `Bae SooMin`,
  `BaeSooMin`,
  `Bae Soo-Min`,
  `Bae Soo Min`,
  `배수민`,
  `裵秀珉`,
  `Sieun`,
  `시은`,
  `ParkSiEun`,
  `Park SiEun`,
  `Park Si-Eun`,
  `Park Si Eun`,
  `박시은`,
  `朴蒔恩`,
  `Isa`,
  `아이사`,
  `LeeChaeyoung`,
  `Lee Chaeyoung`,
  `Lee Chae-young`,
  `Lee Chae young`,
  `이채영`,
  `李彩煐`,
  `Seeun`,
  `세은`,
  `윤세은`,
  `YoonSeeun`,
  `Yoon Seeun`,
  `Yoon Se-eun`,
  `Yoon Se eun`,
  `尹勢銀`,
  `Yoon`,
  `윤`,
  `Shim Jayoon`,
  `ShimJayoon`,
  `Shim Ja-yoon`,
  `Shim Ja yoon`,
  `심자윤`,
  `沈姿潤`,
  `J`,
  `재이`,
  `JangYeeun`,
  `Jang Yeeun`,
  `Jang Ye-eun`,
  `Jang Ye eun`,
  `장예은`,
  `張叡恩`,
];

export const stayc_gradient_first = "#ffffff"; //белый
export const stayc_gradient_second = "#d65676"; // розовый

export const stayc_gradient =
  "linear-gradient(to right bottom, #ffffff, #e9d9f1, #e1b0d6, #de84ac, #d65676)";
